### ISSUE TITLE
toString might crash

### ISSUE THREAD

**Issue by tbiesemann** [sinonjs/formatio#25]
* library version : @sinonjs/formatio@^3.1.0
* Environment   : node/ sinon/mocha

Calling sinon.assert.calledWith fails, if the stub was called with an object having a toString method  which throws.

**How to reproduce**

```js		
it('shall reproduce formatio bug', function () {
	const poison = {
		toString: () => {
			throw new Error("Boom");
		}
	};

	const myStub = sinon.stub();
	myStub(poison);

	sinon.assert.calledWith(myStub, "42");
});
```		

Expectation is to see a sinon error message like "expected stub to be called with..." instead of a formatio error.

I think a try/catch and swallow the error should be sufficient.

**Comment by mroderick** [comment]
Edit: enable syntax highlighting

**Comment by mroderick** [comment]
This package has been deprecated in favour of using `util.inspet` in the Sinon projects
