### ISSUE TITLE
Non-backward-compatible change of constructorName

### ISSUE THREAD

**Issue by snakamura** [sinonjs/formatio#27]
* library version : 3.1.1
* Environment   : node 10.15.1

**What did you expect to happen?**

`formatio.constructorName(Object.create(null, {}))` returns an empty string.

**What actually happens**

It throws an error: `TypeError: Cannot read property 'displayName' of undefined`

**How to reproduce**

    const formatio = require('@sinonjs/formatio');
    console.log(formatio.constructorName(Object.create(null, {})));

At 3.1.0, `constructorName` returned an empty string if an argument didn't have a constructor, but now it throws an error.

We faced this issue when we used sinon and should-sinon. Here is a snippet to reproduce the original issue we had.

    const sinon = require('sinon');
    require('should-sinon');

    const stub = sinon.stub().returns();
    const o = Object.create(null, {});
    stub(o);
    stub.should.be.calledWithExactly(o);

With 3.1.0, this snippet runs without errors, but with 3.1.1 it throws an error: `TypeError: Cannot read property 'displayName' of undefined`.

**Comment by nasvillanueva** [comment]
Hopefully sinonjs/commons#12 would fix it.

**Comment by mantoni** [comment]
I've just release `@sinonjs/commons v1.3.1`. Can you verify that fixed it?

**Comment by snakamura** [comment]
Yes, it does fix the issue. Thank you!
