### ISSUE TITLE
Update sinonjs/samsam in package.json

### ISSUE THREAD

**Issue by kr3ad** [sinonjs/formatio#32]
> We understand you have a problem and are in a hurry, but please provide us with some info to make it much more likely for your issue to be understood, worked on and resolved quickly.

* library version : 3.2.1
* Environment   : 
* Example URL   : 
* Other libraries you are using: sinon

**What did you expect to happen?**

**What actually happens**

We need the updated version of sinonjs/samsam (3.3.3) as a dependency of formatio because of a need to update lodash version that it uses (https://github.com/sinonjs/samsam/pull/72)

**How to reproduce**
> Describe *with code* how to reproduce the faulty behaviour,
> or link to code on JSBin or similar

**Comment by mroderick** [comment]
This project currently specifies

`"@sinonjs/samsam": "^3.1.0"`

https://stackoverflow.com/questions/22343224/whats-the-difference-between-tilde-and-caret-in-package-json

This means that when installing `formatio` it will install the latest `3.x` version of `@sinonjs/samsam`, which is `v3.3.3`.

Try installing `@sinonjs/formatio` again.
